boons/boons.yml

There was the word accomplishing twice in the haste boon description.

Simple correction of haste boon

---

boons/boons.yml

Removed duplicate dice explosion reminder in Heal. 
Added Lethal Damage notice to Regeneration.
Added power levels to Retributive Barrier.
Changed restoration to also work with other attributes.

Heal, Regeneration, Retributive Barrier, Restoration fixes

---

banes/banes.yml

Surprised is still 0, since it's N/A and dictated by the DM. Immobile is updated and a run through Boons/Banes reveals it's a min pre-reqof 1 across the board aside from Surprised now.

Banes min-prereq now 1.

---

feats/feats.yml

Made it so it requires both, not either or to fix the feats page. Fleet of Foot has no issue afaik in feats.yml, that's site-side.

Multi-Target Boon Expert requirements fixed.

---

feats/feats.yml

It referenced Fortitude before, now it references Might, for the updated rules.

Armor Mastery references Might now.

---

boons/boons.yml

Added some HTML tags to Barrier boon effect for proper rendering on a web browser.
Prior:
> When you invoke this boon, you must use multi-targeting to create a specific area of effect to define the space of your barrier. Upon successful invocation, choose a number of available properties for your wall based on your power level: **Power Level 3 -** Choose 1 property: Damaging (1d4), Obscuring, Hindering **Power Level 5 -** Choose 2 properties: Damaging (1d8), Obscuring, Hindering, Baneful, Mobile **Power Level 7 -** Choose 3 properties: Damaging (1d10), Obscuring, Hindering, Baneful, Mobile, Impassable **Power Level 9 -** Choose 4 properties: Damaging (2d6), Obscuring, Hindering, Baneful, Mobile, Impassable **Damaging:** A creature who ends its turn within the barrier or willingly enters …

Add HTML tags to Barrier boon for proper rendering

---

feats/feats.yml

Found this typo that prevents the feat's effect text to render properly.

Fix typo in list closing tag in Attribute Substitution feat

---

feats/feats.yml

Renamed `Knowledge` to `Knowledge (I - III)` to maintain the consistency for feat with multiple tiers to have the tier range expressed in the name (e.g. `Battlefield Sentinel (I - V)`).

Add tier info to Knowledge feat name to maintain consistency

---

feats/feats.yml

Fix repeating tier level. Now tier levels are ascending.

Fix incorrect tier levels for Inspiring Champion feat

---

feats/feats.yml

Fix incorrect yaml syntax that would prevent the prerequisites to be properly parsed.

Fix prerequisites for Fleet of Foot feat

---

banes/banes.yml
feats/feats.yml

Follows #137.
Remove useless line breaks at the end of effect description.

Remove useless line breaks

---

boons/boons.yml

Follows #137.
Removed unneccessary list from Invisible boon effect since this boon has only one power level.

Invisible remove list

---

core/src/01-character-creation/01-chapter-one.md
feats/feats.yml

**Changes:**
- Renamed `Hallucination (Mass)` to `Hallucination - Mass` as suggested in #167. Closes #132.
- Added missing attributes to Druid and Arcane Protector, each missing a score 3 (example characters from Google Drive were used as references)
- Removed obsolete reference to `Master Shifter` in the Druid feat table
**Regarding `Master Shifter` removal**
With the removal of `Master Shifter` the Druid has now 3 feat points to spend at level 1. 
I didn't insert a new feat because I'm not sure of what to do. 
We could either go for `Boon Focus II (Shapeshift)`, so that at level 2 the Druid can purchase `Boon Focus III (Shapeshift)` and achieve the same effect as `Master Shifter`, or we can purchase `Boon Focus I (Heal)`, to underline the healing capabilities of this class.

Various fixes

---

core/src/06-combat/01-chapter-six.md

`Disrupting Attack` should follow the same rules as an `Exceptional Success`, i.e. `10 over defense` instead of `10+ damage`.

Update Disrupting Attack to 10 over defense rule

---

core/SRD.md

**Changelog**
- Added note `Beyond 10th Level` in Chapter 7
- Updated XP system paragraph name in Chapter 7
- Second pass of `Supernatural` to `Extraordinary`
- Removed conflicting line in `Multi-Attack Specialist` (#202)
- Updated `normal action` to `major action` in Boss Actions (#202)
- Added `Barrier` boon
- Reordered feats by alphabetical order (#203)
- Renamed `Hallucination (Mass)` to `Hallucination - Mass`
- Addedd `Summon Creature` boon
- Removed duplicate `Reaching Zero Hit Points`
- Added longer duration on fail note to `Resist Banes`
- Updated `Minor Actions` paragraph
- Added note on forced movement to `Opportunity Attacks`
- Specified number of targets in `Defend`
- Added `Free Actions` paragraph
- Updated `Alternate Form` feat (#114)
- Removed gender specifics
- Added genre …

SRD Update #2

---

core/SRD.md
feats/feats.yml

I think that is what you intended, since to acquire `Boon Focus` you need to have access to the boon.

Move warning to Boon Access instead of Boon Focus

---

core/SRD.md
core/src/06-combat/01-chapter-six.md

Small wording fix: replaced `ranged` for `projectile` when talking about targeting

Change projetile targets to ranged targets

---

README.md
core/SRD.md
feats/feats.yml

Now `Armor Mastery` cost is 3 in SRD and `feats.yml`.
Update tier prerequisites in SRD.
Update changelog to mention changes to `Armor Mastery`.

Correct Armor Mastery typos

---

core/src/01-character-creation/01-chapter-one.md

- Swap `Perception` score for `Agility` score in `Ranger` example to qualify for `Master Tracker` feat.
- Add tier number to feats
- Remove `Armor Mastery` for `Paladin` since it cannot longer afford it (`Attribute Substituion II` cost 4 points and `Armor Mastery` cost 3, and `Attribute Substituion II` is essential for the `Paladin`).

Update Archetype Feat Recommendations

---

core/SRD.md
core/src/06-combat/01-chapter-six.md

Updated reference to the `Swift` property when speaking about initiative rolls. 
A note for the `Slow` property should also be added.

Update reference to Swift property in Roll for Initiative

---

banes/banes.yml

Added losing the Might bonus to Guard. If it's not supposed to be lost, writing "The target loses their attribute bonuses to their defense scores" is unclear.

Clarify Fatigue tier 2

---

banes/banes.yml
boons/boons.yml
core/SRD.md
core/src/00-introduction/01-introduction.md
core/src/01-character-creation/01-chapter-one.md
core/src/02-actions-attributes/01-chapter-two.md
core/src/03-feats/01-chapter-three.md
core/src/04-wealth-equipment/01-chapter-four.md
core/src/05-banes-boons/01-chapter-five.md
core/src/06-combat/01-chapter-six.md
core/src/07-running-the-game/01-chapter-seven.md
feats/feats.yml

Replaced `’` (apostrophe) for `'` (typewriter apostrophe). See #312.

Apostrophe Fix 

---

core/src/02-actions-attributes/01-chapter-two.md

The ability to apply Legend Points after the result goes against the "every roll matters" mantra to me and seems a bit min-maxy. With the previous rules, you would never want to apply the points prior to the roll as you could potentially waste them if you had a high initial roll.  Forcing the PC to commit to spending points  prior to the roll in an attempt to ensure a more legendary outcome makes the decision of spending the points more important.

Proposed Change to Spending Legendary Points

---

feats/feats.yml

Nothing in the description of Longshot describes a second tier. Remove it.

Remove empty tier2 of Longshot feat

---

CONTRIBUTING.md

The OL community site is now http://community.openlegendrpg.com/ rather than on MightyBell.

Point to new Open Legend community site

---

core/src/07-combat/01-chapter-seven.md

So, here's the thing:
Disrupting Strike technically says "uses normal damaging attack rules", which means that if we don't specify otherwise, it **BOTH** triggers a bane and **ALSO** cancels a boon. I propose we streamline and make both part of _Extraordinary Success_.
Honestly, after seeing what people can do at high levels after layering a number of boons on top of each other, I actually think this will be a HUGE help in terms of balance, it means that you don't have to risk wasting an action to "Shoot the flying wizard out of the sky" or "Force the Ghost to manifest, canceling Insubstantial".

Move "Disrupting Attack" to be an alternate option under "Extraordinary success"

---

README.md
feats/feats.yml

@brianfeister `Ferocious Minions` prerequisites are wrong on the site, because I confused `Animation` with `Summon Creature` (somehow) while editing. Now they are correct. I also bumped the changelog to reflect this change.

Wrong Ferocious Minions prerequisites (CRITICAL)
