boons/boons.yml
I sorted them alphabetically instead of by category, so Perception follows after Movement instead of going at the beginning, so there's no indication that it's a Mental skill instead of a Supernatural one.
=> Sorted all attributes alphabetically

banes/banes.yml, boons/boons.yml, feats/feats.yml
Went through and did a pass for typos in the above files, just forked, edited locally, commited & pushed, and then submitted a pull request. If there's a way you prefer this done let me know.
=> Typos fixed for Boons, Banes, and Feats.

banes/banes.yml
As per issue #63, added movement to slowed bane, and alphabetically sorted attributes.
=> Added Movement to Slowed Bane

feats/feats.yml
Sorted all attributes and placed all feat requirements below attribute requirements, where applicable.
=> Feats Attribute Sort

banes/banes.yml
This one was easy. I sorted all the attributes alphabetically, with no regard to what category they're in (i.e. Mental vs Supernatural).
=> Bane Attribute Sort

feats/feats.yml
extra commit because I forgot to add colons to Ageless, other than that looks fine.
Check it out and merge if you like it.
=> Feat Style Implemented

feats/feats.yml
Found these errors while reading through the file.
I'm not sure if the last commit contains errors or if they were intended to be like this, but I included it anyway just in case.
=> Fix errors in feats.yml

feats/feats.yml
=> Energy Resistence Clarification

core/src/01-character-creation/01-chapter-one.md
Quick edit to the summary for character attributes since Fortitude is no longer the requirement for armour.
=> Changed Might Attribute to reflect Armor Change.

README.md, boons/boons.yml
Matches power levels in description now. Fixes #107 
Added changelog, lists changes in simplified form with a link to the commit list for people who want more detail.
=> Changelog and minor Genesis fix.

feats/feats.yml
Exactly what it says on the tin.
=> Prescience for Lightning Reflexes

README.md
Update the changelog to reflect the commits until Nov 15, 2016. SRD updates were ignored. Changelog is sorted in descending date.
=> Update changelog to reflect commits until Nov 15, 2016

boons/boons.yml
Found another one, now the lists are displayed properly.
=> Fix closing tags in Aura boon effect

banes/banes.yml, boons/boons.yml, feats/feats.yml
And it's done. Resolves issue #134.
Left empy string for items with no special notes. If you want to remove the special key for items with no special note I can do that, it's a simple replace.
Found other issues while changing the code, will open more pr soon.
=> Special note refactoring

banes/banes.yml, boons/boons.yml, feats/feats.yml
Follows #137.
I'm not sure about this one, so I move it to a separate pull request.
=> Combat follow through requirement refactor

banes/banes.yml, boons/boons.yml, feats/feats.yml
=> Remove empty special key

feats/feats.yml
=> Implement multiple attributes prerequisite for Fast Tracker

feats/feats.yml
fixed consistency for 5 squares into 25 feet.
=> squares -> feet

README.md
Changelog updated as requested in #179.
=> Changelog update

core/SRD.md, core/src/01-character-creation/01-chapter-one.md
Updated `Aid` reference to `Bolster` in Bard example.
Updated `Aid` to `Bolster` in SRD (in the hope I get it right).
=> Aid reference update

core/src/07-running-the-game/01-chapter-seven.md
Small typo and trailing space removal
=> Correct typo in Chapter 7

boons/boons.yml, feats/feats.yml
This time it should be alright.
=> Alphabetical order

core/SRD.md, core/src/07-running-the-game/01-chapter-seven.md, feats/feats.yml
=> Feats: Boon Focus & Bane Focus

core/SRD.md
Please remember to reflect changes in the SRD as well.
Chapter 0 to 3 are now again in sync.
=> SRD Resync

banes/banes.yml, core/SRD.md, feats/feats.yml
Changed `Battlefield Punisher - Slowed` and `Forced Move` to work on feet instead of squares.
=> Squares to feet

boons/boons.yml, core/SRD.md
=> Remove Retributive Barrier in favor of Barrier boon

README.md
=> Update Changelog to 2017/01/13

README.md, core/SRD.md
**Changelog:**
- Fixes #279 in conjunction with #281 
- Update changelog
=> Changelog Update & Multi-Target Boon Expert fix

core/src/01-character-creation/01-chapter-one.md
Space was added on line 717 of character creation.
Original: *Open Legend*gives you.....
Fixed: *Open Legend* gives you.....
=> Minor formatting fix

core/SRD.md, core/src/01-character-creation/01-chapter-one.md
fix to grammar, first sentence
=> Minor Grammar Fix to Lucky Perk

boons/boons.yml, core/SRD.md
Update PL according to the new change
=> Fix Shapeshift PL

core/src/05-wealth-equipment/01-chapter-five.md
=> Fixed lasergun, revolver, handgun range back to Close Ranged

feats/feats.yml
Indomitable Resolve has 3 level of the feat so should have increasing bonuses to Resolve.
=> Indomitable Resolve's increasing bonus

core/src/07-combat/01-chapter-seven.md
I changed "boon" for "bane" in the "Make a Bane Attack" section of chapter 7.
=> Make a Bane Attack text error

core/src/09-special-equipment/01-chapter-nine.md
=> fixes a typo in Chapter 9
